import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]
working_directory = "None"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 18

[font.normal]
# family = "Liga SFMono Nerd Font"
family = "JetBrainsMono Nerd Font Mono"
style = "Thin"

[font.offset]
# x = 1
y = 10

[font.glyph_offset]
# x = 1
y = 5

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[mouse]
hide_when_typing = false

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 1

[window.padding]
x = 50
y = 5
